### ISSUE TITLE
Problem when using with Arduino Nano to read temperature from LM35 

### ISSUE THREAD

**Issue by ChetanAmrao** [souviksaha97/MCP3202#2]
I downloaded the repo to try the ADC_test.ino but I cannot see any SPI values on the serial monitor all i see is 0 0 for both channels

Do i need to make any changes to the program?
my connections:
> i have not used your same circuit
> i connected the miso, mosi, ss, 5v, gnd to the MCP3202 from the Nano

can you suggest anything? 
thanks

**Comment by souviksaha97** [comment]
How have you hooked up the LM35?
Have you got the MISO, MOSI, CLK and SS pins right?

**Comment by ChetanAmrao** [comment]
thanks for the quick reply 
i am using a custom board so i made a wrong connection, should have checked that first before making an issue

i connected a pot to it and now i see 0-4096 range on the spi
![image](https://user-images.githubusercontent.com/32968090/78642939-2146af80-78d1-11ea-934f-62391aa6959b.png)

i have to find the same library for raspberry pi now, we can close this issue
